name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: 'npm'
        cache-dependency-path: |
          lib/package-lock.json
          example-nextjs/package-lock.json
    - run: npm install
      working-directory: lib
    - run: npm run build
      working-directory: lib
    - run: npm install
      working-directory: example-nextjs
    - run: npm test
      working-directory: example-nextjs
